### ISSUE TITLE
Browser - TypeError: 'fetch' called on an object that does not implement interface Window

### ISSUE THREAD

**Issue by CoryCasanave** [rubensworks/fetch-sparql-endpoint.js#27]
Testing fetch from the browser using Browerify throws the error: `TypeError: 'fetch' called on an object that does not implement interface Window`, the exception is on line 101 of "SparqlEndpointFetcher.js"
         
`const httpResponse = await this.fetchCb(url, { headers });`

Tried in Chrom and Firefox. The same code run outside the browser (in Webstorm) returns the proper results. The code is from the published example. I am new to running node.js code in the browser so it may be an error on my part.
To eliminate other variables the method "stuff" is executed in both cases:
```
const fetcher = require("fetch-sparql-endpoint");

const myFetcher = new fetcher.SparqlEndpointFetcher();

async function stuff() {
  const bindingsStream = await myFetcher.fetchBindings('https://dbpedia.org/sparql', 'SELECT * WHERE { ?s ?p ?o } LIMIT 100');
  bindingsStream.on('data', (bindings) => console.log(bindings));
}

exports.fetcher = fetcher;
exports.myFetcher = myFetcher;
exports.stuff = stuff;
stuff();
global.fetcher = exports;
```

**Comment by rubensworks** [comment]
Thanks for reporting!
I suspect this is a bug on my end, as I never actually tested this in the browser.

Note to self: seems similar to this: https://github.com/feathersjs-ecosystem/feathers-rest/issues/54

**Comment by rubensworks** [comment]
Note that you _may_ be able to temporarily fix this as follows:

```
new fetcher.SparqlEndpointFetcher({ fetch: fetch.bind(window) });
```

**Comment by CoryCasanave** [comment]
Yes, the temporary fix worked. Thanks! In the meantime, I found sparql-http-client so need to see if there is some advantage of one over the other now that they both work.
