### ISSUE TITLE
Return of "Header" variables

### ISSUE THREAD

**Issue by CoryCasanave** [rubensworks/fetch-sparql-endpoint.js#28]
To make a nice table from generic query results you need to know what may come back. Is there any facility for getting all the possible return variables?
e.g. "Select * {?Person a :Person, optional {?Person :hasName ?Name}}"

Would return ["Person", "Name"]

**Comment by rubensworks** [comment]
While this doesn't appear to be documented yet, a `variables` event should be emitted before the bindings are produced.

So something like this should give you the variables:
```javascript
resultStream.on('variables', (variables) => console.log(variables));
```

**Comment by CoryCasanave** [comment]
Thanks! The implementation I have today based on Stardog uses the "[spec](https://www.w3.org/TR/sparql11-results-json/)" JSON return structure that has headers and bindings:
```
{
  "head": { "vars": [ ]
  } ,
  "results": { 
    "bindings": [
      {...
```
This is what I will try and convert the results to. It would be nice if this were an option. Please consider it a requested feature.

**Comment by rubensworks** [comment]
This is actually the format this library retrieves from the SPARQL endpoint.
If you want this format directly, then this library may not even be needed.
A simple fetch with `Accept` header set to `application/sparql-results+json` should be sufficient.
