### ISSUE TITLE
AbortController problem for update queries when bundled

### ISSUE THREAD

**Issue by smeckler** [rubensworks/fetch-sparql-endpoint.js#43]
Hi Ruben,

thank you for this library. It works well but I encountered a small problem with the AbortController when sending update queries. It's working when executed with Node, but the 'fetchUpdate' function has an error when it's bundled (with browserify or React).

- JavaScript project
- fetch-sparql-endpoint v2.3.2
- abort-controller v3.0.0

Here is the problem in the browser:
```js
const abort_controller_1 = require("abort-controller");

async fetchUpdate(endpoint, query) {
	const abortController = new abort_controller_1.AbortController(); // TypeError: abort_controller_1.AbortController is not a constructor
	const init = {
		method: 'POST',
		headers: {
			'content-type': 'application/sparql-update',
		},
		body: query,
		signal: abortController.signal,
	};
	await this.handleFetchCall(endpoint, init, { ignoreBody: true });
	abortController.abort();
}
```

A quick workaround was:
```js
    let abortController;
    if (typeof window === 'undefined') { // --> nodeJS
        abortController = new abort_controller_1.AbortController();
    } else { // --> browser
        abortController = new AbortController();
    }
```

**Comment by rubensworks** [comment]
Hmm, this seems to be a bug in `abort-controller`: https://github.com/mysticatea/abort-controller/issues/32

Looks like it can be fixed by moving towards the default export of `AbortController` instead of its named export.

A PR is definitely welcome! :-)
