### ISSUE TITLE
Support for RDF-star?

### ISSUE THREAD

**Issue by benjaminaaron** [rubensworks/fetch-sparql-endpoint.js#60]
When fetching statements about statements (RDF-star), they appear like this:

![Screenshot 2023-03-02 at 09 51 04](https://user-images.githubusercontent.com/5141792/222378630-e555895d-3d2a-48ec-a6e8-653bb67f44e0.png)

In the GraphDB the respective triple looks like this:

![Screenshot 2023-03-02 at 09 51 42](https://user-images.githubusercontent.com/5141792/222378795-1d1fcacc-4a7a-428a-934d-aca7fa8e9de8.png)

My code to fetch the bindings is the following:

```js
import { SparqlEndpointFetcher } from "fetch-sparql-endpoint";
const sparql = new SparqlEndpointFetcher();

async function fetch() {
  const bindingsStream = await sparql.fetchBindings('http://localhost:7200/repositories/dev', 'SELECT * WHERE { ?s ?p ?o }')
  bindingsStream.on('data', (resultRow) => {
    console.log(resultRow)
  });
}

await fetch()
```

Is there a way to map this long identifier in `urn:rdf4j:triple` to a triple? Like a hash-sum or something like this 🤔

**Comment by benjaminaaron** [comment]
Ohh, it's base64 encoded! I just decoded it correctly to:
`<<<http://dev.de/default#Projects> <http://dev.de/default#hasProject> <http://dev.de/default#AkteX>>>`
👍

**Comment by rubensworks** [comment]
The underlying SPARQL results parsers of this library do already support RDF-star and SPARQL-star as of recently.
So if your querying from an engine that adheres to the [RDF-star spec](https://w3c.github.io/rdf-star/cg-spec/editors_draft.html#sparql-star-query-results-json-format), then this lib should be able to handle it.

It looks like rdf4j uses a non-standard serialization approach for nested triples, so this library will not be compatible with it unfortunately.

**Comment by benjaminaaron** [comment]
I see, thanks. Surprising that the GraphDB engine doesn't support this yet. Maybe they will in a future release.
