### ISSUE TITLE
SparqlEndpointFetcher.fetchBindings does not work in Node 18

### ISSUE THREAD

**Issue by pogi7** [rubensworks/fetch-sparql-endpoint.js#71]
I have this code which is using `SparqlEndpointFetcher.fetchBindings`

```typescript
/**
 * RawSparqlQuery returns the JSON data fetched from the server
 * @param query - The raw SPARQL query as a string
 * @returns A promise that resolves with the data as a JSON object, or null if an error occurred
 */
export async function RawSparqlQuery(query: string): Promise<Record<string, any>[]> {
  // Create a new instance of the SparqlEndpointFetcher
  const fetcher = new SparqlEndpointFetcher({ timeout: 6000 });

  const ENDPOINT = `https://dbpedia.org/sparql`;
  const QUERY = `SELECT * WHERE { ?s ?p ?o } LIMIT 100`;

  // Send the query to the Fuseki database
  const responseStream = await fetcher.fetchBindings(ENDPOINT, QUERY);

  return new Promise((resolve, reject) => {
    const results: Record<string, any>[] = [];

    responseStream.on('data', (bindings) => {
      // Push each item into the results array
      results.push(bindings);
    });

    responseStream.on('end', () => {
      // Resolve the Promise with the results array when the stream ends
      resolve(results);
    });

    responseStream.on('error', (error) => {
      reject(error);
    });
  });
}
```

The `await fetcher.fetchBindings(ENDPOINT, QUERY)` call currently fails with the following error message 

> Receiving following error:
> Error: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal

The error does not happen when I'm on VSCode 1.78.2 or below:

> Version: 1.78.2
> Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
> Date: 2023-05-10T15:00:40.428Z
> Electron: 22.5.2
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Darwin arm64 22.6.0
> Sandboxed: No

I only see the ~~code~~ bug when I'm on VSCode 1.80.0 or any version of VSCode which has a nodeJS version of 18 or higher.

**Comment by rubensworks** [comment]
Are you sure you're using the latest version?

**Comment by pogi7** [comment]
@rubensworks Yes, I was using `v4.1.0` 

https://www.npmjs.com/package/fetch-sparql-endpoint/v/4.1.0

**Comment by rubensworks** [comment]
We probably need to add [this](https://github.com/rubensworks/fetch-sparql-endpoint.js/blob/master/lib/SparqlEndpointFetcher.ts#L154-L155) to [here](https://github.com/rubensworks/fetch-sparql-endpoint.js/blob/master/lib/SparqlEndpointFetcher.ts#L222).

Until this issue is fixed, removing the timeout should make it work.

**Comment by rubensworks** [comment]
This issue should be resolved in recent versions of this lib.
If this problem should still occur for you, please let me know.
